@startuml

class addressInfo {
+name
+phoneNumber
+address
+addressInfo()
+set_name(name)
+set_phoneNumber(phoneNumber)
+set_address(address)
+get_name():string
+get_phoneNumber():string
+get_address():string
}

class addressList {
+addressList:list<addressInfo>
+add(info:addressInfo)
+remove(info:addressInfo)
+update(info:addressInfo,newInfo:addressInfo)
+getAt(index):addressInfo
+searchByName(name):addressInfo
+searchByPhoneNumber(phoneNumber):addressInfo
+sort()
+writeDB()
+readDB()
+saveFile()
+loadFile()
}

class addressListUI {
+list:addressList
+printMainmenu()
+selectMenu():menu
+inputInfo()
+deleteInfo()
+updateInfo()
+viewAllList()
+searchByName()
+searchByPhoneNumber()
+writeDB()
+readDB()
+saveFile()
+loadFile()
}

addressInfo "*" <--- "1" addressList
addressList <--- addressListUI

@enduml
